name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B test

    - name: Send Email Notification
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: GitHub Actions CI build ${{ job.status }}
        to: s.sukriti2001@gmail.com
        from: OnTrack-CI <${{ secrets.EMAIL_USERNAME }}>
        body: |
          📣 CI Build Notification

          ✅ Status: ${{ job.status }}
          🔀 Branch: ${{ github.ref }}
          📦 Commit: ${{ github.sha }}
          🔗 Repo: ${{ github.repository }}
